DROP DATABASE IF EXISTS `y352dczozb21se60`;
CREATE DATABASE `y352dczozb21se60`;
USE `y352dczozb21se60`;

DROP TABLE IF EXISTS burgers_data;
CREATE TABLE burgers_data
(
	id int NOT NULL AUTO_INCREMENT,
	name varchar(255) NOT NULL,
	devoured BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (id)
);
